version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: Reynaldo
      POSTGRES_PASSWORD: Dirksen
      POSTGRES_DB: car_registration
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "4444:4444"
    environment:
      DB_USER: car_user
      DB_PASS: password
      DB_NAME: car_registration
      DB_HOST: localhost
      DB_PORT: 5432
      ACCESS_TOKEN_SECRET: myaccesstokensecret
    depends_on:
      - db
    
